// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuclhtppybmxeedsffks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Y2xodHBweWJteGVlZHNmZmtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTY0OTcsImV4cCI6MjA2OTA3MjQ5N30.5udP92AZFXhlul78ZqakJ4lEO7ftgwAvIXaVKD1FlNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});